"""Blog post metadata for blog.html and the per-post blog-<slug>.html pages.

Those pages are generated by cv_to_html.py from the data below (they are NOT
hand-edited). To add or change a post, edit this file and the Markdown body it
points at, then run:

    venv/bin/python cv_to_html.py

Post bodies are authored as **Markdown** in posts/*.md and converted to HTML at
build time. Write math in LaTeX syntax ($...$ inline, $$...$$ display) and set
"math": True so KaTeX loads on that page; fence code blocks with a language tag
(```bash, ```python, ```cpp) and set "code": True so Prism highlights them.

Each post is a dict:
    slug    — URL slug; the page is written to blog-<slug>.html
    title   — post title (also the <h1> and the browser tab title)
    date    — display date string
    source  — path to the Markdown body, relative to the repo root
    excerpt — one- or two-sentence teaser shown on the blog.html index card
    tags    — list of tag strings
    repo    — optional URL to the project's source repository
    math    — True to load KaTeX on this post's page
    code    — True to load Prism on this post's page

POSTS is rendered in list order, so keep the newest post first.

Images live in images/<slug>/ and are referenced from the Markdown by their path
relative to the repo root (e.g. images/2d-ipp-cfar/foo.png), because the
generated HTML sits at the root.
"""

POSTS = [
    {
        "slug": "2d-ipp-cfar",
        "title": "A 2D CFAR Detector with Intel IPP",
        "date": "August 18, 2026",
        "source": "posts/2d-ipp-cfar.md",
        "excerpt": "Finding small, bright clusters of pixels — stars, or man-made "
                   "objects in SAR imagery — against a non-uniform background where "
                   "simple thresholding fails. A 2D Constant False Alarm Rate detector "
                   "in C++, built on Intel's Integrated Performance Primitives and "
                   "cross-checked against a Python implementation.",
        "tags": ["Signal Processing", "C++", "Intel IPP", "OpenCV", "Computer Vision"],
        "repo": "https://github.com/dennisfgardner/2D_ipp_CFAR",
        "math": False,
        "code": True,
    },
]
