"""Blog post content for blog.html.

blog.html is generated by cv_to_html.py from the data below (it is NOT
hand-edited). To add or change a post, edit this file, then run:

    python3 cv_to_html.py

Each post is a dict:
    id       — HTML anchor id (e.g. "post1")
    title    — post title
    date     — display date string
    content  — the post body as raw HTML (paragraphs, <h3>, <blockquote>, ...)
    tags     — list of tag strings
    comments — list of {"author", "date", "text"} dicts

NOTE: the posts below are still AI-generated placeholder content.
"""

POSTS = [
    {
        "id": "post1",
        "title": "The Future of Web Development in 2025",
        "date": "March 15, 2025",
        "content": """                <p>As we navigate through 2025, the landscape of web development continues to evolve at an unprecedented pace. From AI-powered design tools to innovative frontend frameworks, the industry is experiencing a renaissance of creativity and efficiency.</p>

                <h3>AI-Driven Development</h3>
                <p>Perhaps the most significant shift we're witnessing is the integration of artificial intelligence into the development workflow. Tools that can generate code based on natural language prompts have become sophisticated enough to handle complex tasks that would have taken hours to code manually just a few years ago.</p>

                <blockquote>The rise of AI assistants has not replaced developers but has transformed our role from coding every line to becoming architects who guide these intelligent systems toward creating elegant solutions.</blockquote>

                <p>These AI partners are particularly revolutionary for prototyping, allowing developers to iterate through ideas at lightning speed. The most exciting aspect is how they're democratizing web development, making it accessible to those without traditional coding backgrounds.</p>

                <h3>WebAssembly Dominance</h3>
                <p>WebAssembly (Wasm) has finally reached the tipping point where it's becoming standard in production environments. The ability to run near-native performance code in the browser has opened doors to applications that were previously unimaginable in a web context.</p>

                <p>Complex 3D visualizations, real-time video processing, and intensive computational tasks now run smoothly in browsers across all devices. The ecosystem around Wasm has matured, with libraries and frameworks that make it accessible without needing to understand the lower-level details.</p>

                <h3>Micro-Frontends Going Mainstream</h3>
                <p>The micro-frontend architecture has graduated from experimental to essential for large-scale applications. Breaking down monolithic frontends into independently deployable components has proven to be a game-changer for teams working on enterprise applications.</p>

                <h3>Privacy-First Development</h3>
                <p>With global privacy regulations tightening and users becoming increasingly aware of data practices, privacy-first development has moved from a nice-to-have to a fundamental requirement.</p>""",
        "tags": ["Web Development", "AI", "WebAssembly", "Future Tech"],
        "comments": [
            {
                "author": "Alex Johnson",
                "date": "March 15, 2025",
                "text": "Great insights, Dennis! I've been experimenting with some AI coding assistants and they've transformed my workflow.",
            },
            {
                "author": "Sarah Chen",
                "date": "March 16, 2025",
                "text": "The micro-frontend architecture point resonated with me. We've recently transitioned our platform to this approach and while the initial setup was challenging, the long-term benefits have been substantial.",
            },
        ],
    },
    {
        "id": "post2",
        "title": "My Journey Through the Rocky Mountains",
        "date": "February 28, 2025",
        "content": """                <p>Last month, I embarked on an unforgettable adventure through the majestic Rocky Mountains. The breathtaking landscapes and serene wilderness taught me valuable lessons about perseverance and appreciation for nature's wonders.</p>

                <h3>The Decision to Disconnect</h3>
                <p>As someone who spends most days immersed in research and computation, I felt a growing need to disconnect completely. With minimal planning but maximum enthusiasm, I packed my hiking gear and set off on a two-week journey that would challenge me physically and mentally.</p>

                <blockquote>There's something profoundly grounding about being reminded of your limitations by a mountain that has stood for millions of years.</blockquote>

                <h3>Finding My Rhythm</h3>
                <p>By the fourth day, my body began adapting to the altitude, and I settled into a comfortable hiking rhythm. I followed a trail that wound through ancient forests before opening to reveal an alpine lake so vibrantly blue it seemed artificially enhanced – except there was no filter, just nature's incredible palette.</p>

                <h3>Lessons From the Trail</h3>
                <p>The importance of preparation, adaptability in the face of sudden change, and the value of community — the mountains offered clear parallels to research and engineering work. Some of my best ideas have come while on trails, away from screens.</p>""",
        "tags": ["Personal", "Hiking", "Rocky Mountains"],
        "comments": [
            {
                "author": "Michael Wong",
                "date": "February 28, 2025",
                "text": "This resonates deeply with me. I did a similar trip last summer and came back with a completely different perspective on my work-life balance.",
            },
            {
                "author": "James Wilson",
                "date": "March 3, 2025",
                "text": "The parallel between hiking and development is spot on. There's something about rhythmic movement that gets creative juices flowing.",
            },
        ],
    },
]
